
const products = [
  {
    name: "Cytrol 75WP",
    size: "500 g",
    price: 2500.0,
    image: "media/Cytrol-400gms.png",
    category: "Fungicides",
  },
  {
    name: "Rumble 32.5SC",
    size: "1 liter",
    price: 3100.0,
    image: "media/Rumble-500ml.png",
    category: "Fungicides",
  },
  {
    name: "Simazole 50SC",
    size: "500 ml",
    price: 2200.0,
    image: "media/featured1.pngs",
    category: "Fungicides",
  },
  {
    name: "Polard 10EW",
    size: "1 liter",
    price: 2600.0,
    image: "media/Polard-400ml.png",
    category: "Fungicides",
  },
  {
    name: "Spot Fix 33.5SC",
    size: "500 ml",
    price: 2300.0,
    image: "media/spotfix-33.5sc.png",
    category: "Fungicides",
  },
  {
    name: "Orthodox 18.7 WDG",
    size: "500 g",
    price: 3200.0,
    image: "media/orthodox-18.7-wdg.png",
    category: "Fungicides",
  },
  {
    name: "Chlorostrobin 56SC",
    size: "1 liter",
    price: 3600.0,
    image: "media/Chlorostrobin-800ml.png",
    category: "Fungicides",
  },
  {
    name: "Suprazole 60WDG",
    size: "500 g",
    price: 3000.0,
    image: "media/Superazol-500ml.png",
    category: "Fungicides",
  },
  {
    name: "Spotfix Super 35SC",
    size: "500 ml",
    price: 2400.0,
    image: "media/spotfix-super-35sc.png",
    category: "Fungicides",
  },
  {
    name: "Takle 80WDG",
    size: "500 g",
    price: 2800.0,
    image: "media/takle-80wdg.png",
    category: "Fungicides",
  },
  {
    name: "Jupitor 26FS",
    size: "500 ml",
    price: 2300.0,
    image: "media/jupitor-26fs.png",
    category: "Fungicides",
  },
  {
    name: "Dora 25EC",
    size: "1 liter",
    price: 2500.0,
    image: "media/Dora-25EC-250ml.png",
    category: "Fungicides",
  },
  {
    name: "Thiostar M 70WP",
    size: "500 g",
    price: 3300.0,
    image: "media/Thiostar-M-400gms.png",
    category: "Fungicides",
  },
  {
    name: "Coopix-50WP",
    size: "500 g",
    price: 2600.0,
    image: "media/Coopix-500gms.png",
    category: "Fungicides",
  },
  {
    name: "Court 80WP",
    size: "10 kg",
    price: 17825.0,
    image: "media/Court-350gms.png",
    category: "Fungicides",
  },
  {
    name: "Sweet Spot 80WP",
    size: "250 gm",
    price: 525.0,
    image: "media/SweetSpot-250gms.png",
    category: "Fungicides",
  },
  {
    name: "Swing 72WP",
    size: "250 gm",
    price: 765.0,
    image: "media/Swing-350gms.png",
    category: "Fungicides",
  },
  {
    name: "Swing 72WP",
    size: "1000 gm",
    price: 2860.0,
    image: "media/Swing-350gms.png",
    category: "Fungicides",
  },
  {
    name: "Swing 72WP",
    size: "10 kg",
    price: 28205.0,
    image: "media/Swing-350gms.png",
    category: "Fungicides",
  },
  {
    name: "Super Guard 72WP",
    size: "250 gm",
    price: 765.0,
    image: "media/Super-Gaurd-600gms.png",
    category: "Fungicides",
  },
  {
    name: "Super Guard 72WP",
    size: "1000 gm",
    price: 2860.0,
    image: "media/Super-Gaurd-600gms.png",
    category: "Fungicides",
  },
  {
    name: "Super Guard 72WP",
    size: "10 kg",
    price: 28245.0,
    image: "media/Super-Gaurd-600gms.png",
    category: "Fungicides",
  },
  {
    name: "Rignil 0.4G",
    size: "8 kg",
    price: 2460.0,
    image: "media/Rignil.png",
    category: "Fungicides",
  },
  {
    name: "Tara Paidan 4G",
    size: "9 kg",
    price: 4095.0,
    image: "media/tara-paidan-4g.png",
    category: "Fungicides",
  },
  {
    name: "Tara Gold 5G",
    size: "7 kg",
    price: 1680.0,
    image: "media/tara-gold-5g.png",
    category: "Fungicides",
  },
  {
    name: "Rignil 0.4G",
    size: "8 kg",
    price: 2460.0,
    image: "media/Rignil.png",
    category: "GRANULES",
  },
  {
    name: "Tara Paidan 4G",
    size: "9 kg",
    price: 4095.0,
    image: "media/Tara-Paidan-9Kg-Bag.png",
    category: "GRANULES",
  },
  {
    name: "Tara Gold 5G",
    size: "7 kg",
    price: 1680.0,
    image: "media/Tara-Gold-7Kg-Bag.png",
    category: "GRANULES",
  },
  
  
  // herbicides

  {
    name: "Atra Gold 74EC",
    size: "650 ml",
    price: 4435.0,
    image: "media/Atra-Gold-New-Layout.png",
    category: "Herbicides",
  },
  {
    name: "Atra Gold 74EC",
    size: "1000 ml",
    price: 6670.0,
    image: "media/Atra-Gold-New-Layout.png",
    category: "Herbicides",
  },
  {
    name: "Cane Master 50WP",
    size: "1000 gm",
    price: 3490.0,
    image: "media/cane-master-50wp.png",
    category: "Herbicides",
  },
  {
    name: "Weed Master 80WG",
    size: "650 gm",
    price: 3045.0,
    image: "media/weed-master-80wg.png",
    category: "Herbicides",
  },
  {
    name: "Shot Gun 26OD",
    size: "400 ml",
    price: 1285.0,
    image: "media/Shotgun-37OF-1-Ltr.png",
    category: "Herbicides",
  },
  {
    name: "Bentachlor 35WP",
    size: "300 gm",
    price: 1260.0,
    image: "media/bentachlor-35wp.png",
    category: "Herbicides",
  },
  {
    name: "Meture 30WP",
    size: "50 gm Pack",
    price: 920.0,
    image: "media/Meture-30-SL.png",
    category: "Herbicides",
  },
  {
    name: "Meture 30WP",
    size: "100 gm Pack",
    price: 1840.0,
    image: "media/Meture-30-SL.png",
    category: "Herbicides",
  },
  {
    name: "Himore 20EC",
    size: "300 ml",
    price: null,
    image: "media/himore-20ec.png",
    category: "Herbicides",
  },
  {
    name: "G Max Lite 15EC",
    size: "500 ml",
    price: null,
    image: "media/G-Max-Lite-1Ltr.png",
    category: "Herbicides",
  },
  {
    name: "G Max Lite 15EC",
    size: "1000 ml",
    price: null,
    image: "media/G-Max-Lite-1Ltr.png",
    category: "Herbicides",
  },
  {
    name: "Belmark 25SL",
    size: "500 ml",
    price: null,
    image: "media/belmark-25sl.png",
    category: "Herbicides",
  },
  {
    name: "Xtra Care- 23OD",
    size: "500 ml",
    price: null,
    image: "media/xtra-care-23od.png",
    category: "Herbicides",
  },
  {
    name: "Clean Way 55SC",
    size: "500 ml",
    price: 1495.0,
    image: "media/clean-way-55sc.png",
    category: "Herbicides",
  },
  {
    name: "Clean Way 55SC",
    size: "1000 ml",
    price: 2860.0,
    image:"Orthox-800gms",
    category: "Herbicides",
  },
  {
    name: "Maxtrol 38SC",
    size: "1000 ml",
    price: 1840.0,
    image:"media/Maxtrol-38SC-1-Ltr.png",
    category: "Herbicides",
  },
  {
    name: "Short Cut 48SL",
    size: "1000 ml",
    price: 2310.0,
    image:"media/Shortcut-1-Ltr_Black.png",
    category: "Herbicides",
  },
  {
    name: "Pendimethalin 33EC",
    size: "1000 ml",
    price: 2890.0,
    image:"Orthox-800gms",
    category: "Herbicides",
  },
  {
    name: "Shedder 20SL",
    size: "1000 ml",
    price: 2125.0,
    image:"media/Shedder-1-Ltr_Black.png",
    category: "Herbicides",
  },
  {
    name: "Pomaxtra 16OD 400 ml + Pomax Ul",
    size: "Pack",
    price: 2500.0,
    image:"media/Pomaxtra-500ml.png",
    category: "Herbicides",
  },

// Insecticides

  {
    name: "Genitox 30SC",
    size: "100 ml",
    price: 1155.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Pirox Majic-20SG",
    size: "100 gm",
    price: 985.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Axona 20SC",
    size: "250 ml",
    price: 1330.0,
    image:"media/Axona.png",
    category: "Insecticides",
  },
  {
    name: "Axona 20SC",
    size: "500 ml",
    price: 2470.0,
    image:"media/Axona.png",
    category: "Insecticides",
  },
  {
    name: "Stand Out 15SE 250 ml + Super Fly",
    size: "Pack",
    price: 3625.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Trofezon Super 25SC",
    size: "800 ml",
    price: 2730.0,
    image:"media/Trofezon-1-Kg.png",
    category: "Insecticides",
  },
  {
    name: "Vandal 22ZC",
    size: "160 ml",
    price: 1310.0,
    image:"media/Vandal-22-ZC.png",
    category: "Insecticides",
  },
  {
    name: "Vandal 22ZC",
    size: "320 ml",
    price: 2365.0,
    image:"media/Vandal-22-ZC.png",
    category: "Insecticides",
  },
  {
    name: "Cutlas 20SC",
    size: "300 ml",
    price: 1340.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Sunitol 4.3EC",
    size: "400 ml",
    price: 1840.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Nito Power 60WDG",
    size: "100 gm",
    price: 2180.0,
    image:"Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Jumper 10WDG",
    size: "75 gm",
    price: 475.0,
    image:"media/Jumper.png",
    category: "Insecticides",
  },
  {
    name: "Jumper 10WDG",
    size: "300 gm",
    price: 1630.0,
    image:"media/Jumper.png",
    category: "Insecticides",
  },
  {
    name: "Check Worm 5EC",
    size: "75 ml",
    price: 685.0,
    image:"media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Check Worm 5EC",
    size: "150 ml",
    price: 1260.0,
    image:"media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Rignil 5SC",
    size: "480 ml",
    price: 1870.0,
    image:"media/Rignil.png",
    category: "Insecticides",
  },
  {
    name: "Super Lock 34WP",
    size: "100 gm",
    price: 1575.0,
    image:"media/Super-Lock-25-SC-1.png",
    category: "Insecticides",
  },
  {
    name: "Barko 80WDG",
    size: "100 gm",
    price: 2050.0,
    image:"media/Barko.png",
    category: "Insecticides",
  },
  {
    name: "Diden 60WDG",
    size: "100 gm",
    price: 1525.0,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Check Worm Super 9SC",
    size: "200 ml",
    price: 1915.0,
    image:"media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Thomsan-25WDG",
    size: "48 gm",
    price: 265.0,
    image:"media/Thomson-Sachet.png",
    category: "Insecticides",
  },
  {
    name: "Depender 12SC",
    size: "300 ml",
    price: 3255.0,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Hubble 35WG",
    size: "200 gm",
    price: null,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Vepco 40WDG",
    size: "80 gm",
    price: null,
    image:"media/Vapco-20SL-250ml-01.png",
    category: "Insecticides",
  },
  {
    name: "Vepco 20SP",
    size: "250 gm",
    price: null,
    image:"media/Vapco-20SL-250ml-01.png",
    category: "Insecticides",
  },
  {
    name: "Midox 12.5EC",
    size: "500 ml",
    price: null,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Orthox 75SP",
    size: "250 gm",
    price: null,
    image:"media/Orthox-800gms.png",
    category: "Insecticides",
  },
  {
    name: "Crunch 50WDG",
    size: "120 gm",
    image:"media/Orthox-800gms",
    price: null,
    category: "Insecticides",
  },
  {
    name: "Killmite 57EC",
    size: "1000 ml",
    price: null,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Daclotin 12SC",
    size: "400 ml",
    price: null,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Movextra 20SC",
    size: "250 ml",
    price: 2835.0,
    image:"media/Orthox-800gms",
    category: "Insecticides",
  },
  {
    name: "Cumix 10EC",
    size: "250 ml",
    price: 625.0,
    image: "media/Cumix.png",
    category: "Insecticides",
  },
  {
    name: "Cumix 10EC",
    size: "1000 ml",
    price: 1945.0,
    image: "media/Cumix.png",
    category: "Insecticides",
  },
  {
    name: "Coniflex 70WS",
    size: "50 gm",
    price: 725.0,
    image: "media/Coniflex.png",
    category: "Insecticides",
  },
  {
    name: "Coniflex 20SL",
    size: "250 ml",
    price: 1315.0,
    image: "media/Coniflex.png",
    category: "Insecticides",
  },
  {
    name: "Coniflex 20SL",
    size: "1000 ml",
    price: 4855.0,
    image: "media/Coniflex.png",
    category: "Insecticides",
  },
  {
    name: "Coniflex 25WP",
    size: "250 gm",
    price: 865.0,
    image: "media/Coniflex-WP.png",
    category: "Insecticides",
  },
  {
    name: "Pirox Super 50SG",
    size: "50 gm",
    price: 865.0,
    image: "media/Pyrox-Super.png",
    category: "Insecticides",
  },
  {
    name: "Foxal 36SC",
    size: "200 ml",
    price: 1945.0,
    image: "media/Foxal.png",
    category: "Insecticides",
  },
  {
    name: "Foxal 36SC",
    size: "400 ml",
    price: 3730.0,
    image: "media/Foxal.png",
    category: "Insecticides",
  },
  {
    name: "Dalus 10.8EC",
    size: "500 ml",
    price: 1420.0,
    image: "media/Axona",
    category: "Insecticides",
  },
  {
    name: "Trofezon 25WP",
    size: "1000 gm",
    price: 2415.0,
    image: "media/Trofezon-1-Kg.png",
    category: "Insecticides",
  },
  {
    name: "Super Fly 1.8EC",
    size: "400 ml",
    price: 895.0,
    image: "media/Axona",
    category: "Insecticides",
  },
  {
    name: "Super Fly 1.8EC",
    size: "1000 ml",
    price: 2100.0,
    image: "media/Axona",
    category: "Insecticides",
  },
  {
    name: "Darwin 50SC",
    size: "400 ml",
    price: 2920.0,
    image: "media/Darwin.png",
    category: "Insecticides",
  },
  {
    name: "Ripfos 44EC",
    size: "500 ml",
    price: 2470.0,
    image: "media/Ripfos.png",
    category: "Insecticides",
  },
  {
    name: "Latch 5EC",
    size: "400 ml",
    price: 1050.0,
    image: "media/Latch-400ml.png",
    category: "Insecticides",
  },
  {
    name: "Latch 5EC",
    size: "1000 ml",
    price: 2335.0,
    image: "media/Latch-400ml.png",
    category: "Insecticides",
  },
  {
    name: "Jumper 2.5EC",
    size: "250 ml",
    price: 520.0,
    image: "media/Jumper.png",
    category: "Insecticides",
  },
  {
    name: "Jumper 2.5EC",
    size: "1000 ml",
    price: 1470.0,
    image: "media/Jumper.png",
    category: "Insecticides",
  },
  {
    name: "Starfen 10EW",
    size: "500 ml",
    price: 1785.0,
    image: "media/Starfen-10EC-1Ltr.png",
    category: "Insecticides",
  },
  {
    name: "Starfen 10EW",
    size: "1000 ml",
    price: 3490.0,
    image: "media/Starfen-10EC-1Ltr.png",
    category: "Insecticides",
  },
  {
    name: "Brisbane 40EC",
    size: "250 ml",
    price: 815.0,
    image: "media/Brisbane.png",
    category: "Insecticides",
  },
  {
    name: "Brisbane 40EC",
    size: "1000 ml",
    price: 2575.0,
    image: "media/Brisbane.png",
    category: "Insecticides",
  },
  {
    name: "Check Worm 1.9EC",
    size: "200 ml",
    price: 605.0,
    image: "media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Check Worm 1.9EC",
    size: "400 ml",
    price: 1050.0,
    image: "media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Check Worm 1.9EC",
    size: "1000 ml",
    price: 2450.0,
    image: "media/Checkworm.png",
    category: "Insecticides",
  },
  {
    name: "Ecophos 40EC",
    size: "1000 ml",
    price: 3885.0,
    image: "media/Echophos.png",
    category: "Insecticides",
  },
  {
    name: "Unifos 21EC",
    size: "1000 ml",
    price: 2755.0,
    image: "media/Unifos-500ml.png",
    category: "Insecticides",
  },
  {
    name: "Deltamax 36EC",
    size: "1000 ml",
    price: 4070.0,
    image: "media/Delta.png",
    category: "Insecticides",
  },
  {
    name: "Luxan 3SC",
    size: "400 ml",
    price: 970.0,
    image: "media/Axonat",
    category: "Insecticides",
  },
  {
    name: "Reborn 10%",
    size: "4 Ltr",
    price: 2620.00,
    image:"media/Reborn-4Lrtr.png",
    category: "Micronutrients",
  },
  {
    name: "Reborn 10%",
    size: "20 Ltr",
    price: 10000.00,
    image:"media/Reborn-4Lrtr.png",
    category: "Micronutrients",
  },
  {
    name: "Reborn 10%",
    size: "200 Ltr",
    price: 90000.00,
    image:"media/Reborn-4Lrtr.png",
    category: "Micronutrients",
  },
  {
    name: "Tara King (5:15:45)",
    size: "1000 gm",
    price: 1575.00,
    image:"media/Tara-King-10-kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara King (5:15:45)",
    size: "10 kg",
    price: 14280.00,
    image:"media/Tara-King-10-kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tri Power (15:0:30)",
    size: "1000 gm",
    price: 1250.00,
    image:"media/Tri-Power-1-Kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tri Power (15:0:30)",
    size: "10 kg",
    price: 10760.00,
    image:"media/Tri-Power-1-Kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Super (8:8:6)",
    size: "1000 ml",
    price: 1630.00,
    image:"media/Tara-Super-8-8-6-500ml.png",
    category: "Micronutrients",
  },
  {
    name: "Growfert 10%",
    size: "1000 ml",
    price: 1250.00,
    image:"media/Tara-Zinc-Bag-5kg",
    category: "Micronutrients",
  },
  {
    name: "Tara Fixer 5%",
    size: "1000 ml",
    price: 1575.00,
    image:"media/Tara-Fixer-1Ltr.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Green (20:20:20)",
    size: "1000 gm",
    price: 1420.00,
    image:"media/Tar-Green1kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Green (20:20:20)",
    size: "10 kg",
    price: 12810.00,
    image:"media/Tar-Green1kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Zinc 10% Liquid",
    size: "3 Ltr",
    price: 920.00,
    image:"media/Tara-Zinc-Bag-5kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Zinc 10% Liquid",
    size: "20 Ltr",
    price: 6000.00,
    image:"media/Tara-Zinc-Bag-5kg.png",
    category: "Micronutrients",
  },
  {
    name: "Tara Zinc 10% Liquid",
    size: "200 Ltr",
    price: 52000.00,
    image:"media/Tara-Zinc-Bag-5kg.png",
    category: "Micronutrients",
  },
];

async function addproducts() {
  try {
    await Products.insertMany(products);
    console.log("Insecticides added successfully!");
  } catch (error) {
    console.error("Failed to add insecticides:", error);
  }
}
// addproducts();

